name: flutter_pactus_grpc
description: gRPC client for Pactus blockchain. Generated gRPC code for Pactus blockchain services.
version: 0.1.0+1
homepage: https://github.com/esmaeil-ahmadipour/flutter_pactus_grpc

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fixnum: ^1.1.1
  grpc: ^4.0.4
  protobuf: ^4.0.0

dev_dependencies:
  analyzer: ^7.4.5
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
